CREATE TABLE IF NOT EXISTS user_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reporter_user_id INT NOT NULL,
  reporter_role ENUM('DOCTOR','PATIENT') NOT NULL,
  reporter_doctor_id INT NULL,
  reporter_patient_id INT NULL,
  target_user_id INT NOT NULL,
  target_role ENUM('DOCTOR','PATIENT') NOT NULL,
  target_doctor_id INT NULL,
  target_patient_id INT NULL,
  reason_category VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('SUBMITTED','UNDER_REVIEW','ACTION_TAKEN','CLOSED') NOT NULL DEFAULT 'SUBMITTED',
  admin_note TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  INDEX idx_user_reports_reporter (reporter_user_id, created_at),
  INDEX idx_user_reports_target_doctor (target_doctor_id, created_at),
  INDEX idx_user_reports_target_patient (target_patient_id, created_at),
  INDEX idx_user_reports_status (status, created_at),
  FOREIGN KEY (reporter_user_id) REFERENCES users(id),
  FOREIGN KEY (target_user_id) REFERENCES users(id),
  FOREIGN KEY (reporter_doctor_id) REFERENCES doctors(doctor_id),
  FOREIGN KEY (reporter_patient_id) REFERENCES patients(patient_id),
  FOREIGN KEY (target_doctor_id) REFERENCES doctors(doctor_id),
  FOREIGN KEY (target_patient_id) REFERENCES patients(patient_id)
);
